### ISSUE TITLE
0 samples found in every export

### ISSUE THREAD

**Issue by Nyxenova** [tobiashein/FlpBackup#1]
I'm not sure what the issue is but I tried this out and there seems to be a consistent problem throughout every flp saying "Missing samples" pretty much neglecting every audio file.

**Comment by Nyxenova** [comment]
a bit unrelated but I'd like to add this is a very useful tool just wish it could at least work first this is much faster than having every project open and then having FL vigorously exporting them all cause it does take a long time and a lot of resources.

**Comment by Nyxenova** [comment]
so from trying a few more times and looking at logs my only real guess is that the issue is from the fact it's looking in the wrong place perhaps? it doesnt show C:/ in the beginning so I'm only taking a guess.

**Comment by tobiashein** [comment]
Hello Nyxenova,

I had a quick look and I think I know what's happening. It seems that the way file paths are encoded has changed over time. Well, the tool dates back to 2013, around the time of FL Studio 11.0 and hasn't been updated since. Some breaking changes were to be expected.

I've uploaded a [new version](https://github.com/tobiashein/FlpBackup/releases/tag/v0.1.1), hopefully it will fix your issue.

**Comment by Nyxenova** [comment]
I'm genuinely surprised you worked on this thank you very much!!! trying this now for some reason now it wont start exporting if i choose a directory/subdirectory inside Documents Image-Line changed their Project Folder on there which is where a lot of my current Project's are in though for the moment I am currently testing it out at a different one!

**Comment by Nyxenova** [comment]
didnt mean to close it whoops
